### ISSUE TITLE
impossible to find any accessories

### ISSUE THREAD

**Issue by ldb2000** [alex224/homebridge-openwebif-switch#1]
Hi, 

I have installed the home bridge plugin (installation was ok), but I am not able to see anything.

thanks,

Laurent

**Comment by ldb2000** [comment]
It sounds that the issue is about missing plugins:
Error: The requested accessory 'OpenWebifSwitch' was not registered by any plugin.

**Comment by alex224** [comment]
@ldb2000 Hi, are you sure you installed  the plugin with -g option. 
Can you please run "npm -g ls --depth=0" and check if homebridge-openwebif-switch appears. Thanxs.

**Comment by ldb2000** [comment]
you were right. I don't know it was not appearing in the list. I have re-install it and now it is available.
Thanks
